require: rubocop-rspec

Style/StringLiterals:
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-string-literals'
  EnforcedStyle: "double_quotes"
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/FirstArrayElementIndentation:
  Enabled: false

# Ruby 3.1 hash shorthand
Layout/SpaceAfterColon:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

# Default cop settings
AllCops:
  NewCops: enable
